import localFont from "next/font/local";
import "./globals.css";
import { Footer} from "@/components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:'https://ik.imagekit.io/vikramkwh/greenbaywaterdamagepros.com/Water%20Damage%20Restoration%20fevicon.png?updatedAt=1727900548773'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      {/* <Navigation /> */}
      <div>
        {children}
      </div>
      <Footer />
      </body>
    </html>
  );
}
